#pragma once

#include <stdint.h>
#include <fstream>
#include <chrono>
#include <optional>
#include <stdexcept>
#include <iostream>
#include <string>
#include <cstring>
#include <vector>
#include <deque>
#include <thread>
#include <memory>
#include <cstdint>
#include <functional>
#include <mutex>
#include <unordered_map>
#include <cmath>
#include <algorithm>
#include <array>
#include <any>
#include <filesystem>
#include <random>

#include <dlfcn.h>
#include <SDL2/SDL.h>
#include <sys/mman.h>
#include <link.h>
#include <linux/uinput.h>
#include <fcntl.h>